### ISSUE TITLE
Can I access CPU state from Memory implementation?

### ISSUE THREAD

**Issue by gergoerdi** [royaltm/rust-z80emu#2]
I'm working on an emulator of a pre-existing system that uses the memory refresh signal of the CPU to do some data bus manipulation. This requires accessing the CPU state from `Memory::read_mem`. Is there a way to do that?

I tried putting the CPU inside the datatype that describes my peripherals, i.e. something like

```
pub struct HomeLab2 {
    cpu :: Z80CMOS,
    main_ram: [u8; 0x4000],
    pub video_ram: [u8; 0x0400],
    pub video_running: bool,
    pub keys: Keys,
}
```

but this just leads to ownership problems when trying to run the CPU, e.g.:

```
error[E0499]: cannot borrow `*machine` as mutable more than once at a time
   --> src/hl2.rs:137:46
    |
136 | ...et mut cpu = &mut machine.cpu;
    |                 ---------------- first mutable borrow occurs here
137 | ...f let Err(brk) = cpu.execute_with_limit(machine, tsc, before + BLANK...
    |                         ------------------ ^^^^^^^ second mutable borrow occurs here
    |                         |
    |                         first borrow later used by call
```

**Comment by royaltm** [comment]
have you seen https://docs.rs/z80emu/latest/z80emu/host/cycles/index.html#m1-opcode-fetch ?

The CPU refresh register is increased every M1 cycle and Z80 provides its content on the BUS for each M1 cycle (opcode fetch).
This is reflected in the `Memory::read_opcode` method: https://docs.rs/z80emu/latest/z80emu/host/trait.Memory.html#method.read_opcode

You can cache the value of `ir` during `read_opcode` because those are the only points in time that the contents of `r` changes and then use it during other memory operations.

Let your data structure resemble the hardware components:

```
struct HomeLab2 {
    cpu: Z80CMOS,
    control: MemoryUnit,
    ... other emulator vars
}

struct MemoryUnit {
    main_ram: [u8; 0x4000],
    pub video_ram: [u8; 0x0400],
    r: u8 // <- here you can store the content of refresh register
}

impl Memory for MemoryUnit {
...
    fn read_opcode(&mut self, pc: u16, ir: u16, ts: Self::Timestamp) -> u8 {
        self.r = ir as u8;
        ... read memory
    }
}
```

**Comment by royaltm** [comment]
Please let me know if that helps, otherwise the way you want to solve it is conflicting with the Rust mutability rule.

Perhaps more of a Cpu state can be exposed this way via Memory/Io methods or even a reference to the Cpu itself if that does not cut it.

**Comment by gergoerdi** [comment]
Thank you, this is exactly what I needed -- I didn't realize that R is in sync with instruction fetching (I thought the whole point would be that it's independent of what the CPU otherwise does -- *sigh*), and it also never occurred to me that `read_opcode` is given more information from the CPU than normal `read_mem`.
